spring.application.name=registration-system

# MySQL Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/registrationdb
spring.datasource.username=root
spring.datasource.password=YAZEED-aljarwan1927
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Redis Configuration
spring.data.redis.host=redis
spring.data.redis.port=6379
spring.cache.type=redis
spring.cache.redis.time-to-live=60000
# Hibernate / JPA
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#Jobrunr
org.jobrunr.background-job-server.enabled=true
org.jobrunr.dashboard.enabled=true

#Kafka
spring.kafka.bootstrap-servers=host.docker.internal:9092

# --- Consumer Configuration ---
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.properties.spring.deserializer.value.delegate.class=org.springframework.kafka.support.serializer.JsonDeserializer
spring.kafka.consumer.properties.spring.json.trusted.packages=com.example.demo.jpa

# --- Producer Configuration ---
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer




#Liquibase configuration
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.xml
spring.liquibase.enabled=true

#Elide
elide.json-api.enabled=true
elide.json-api.path=/api/v1
elide.security.enabled=false