POST http://localhost:8082/api/v1/user 
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "user",
    "attributes": {
      "name": "yazeded@gmail",
      "password": "password"
    }
  }
}

###
GET http://localhost:8080/api/v1/user

###
POST http://localhost:8082/api/v1/private/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YXplZGVkQGdtYWlsIiwiaWF0IjoxNzUwNTk4MjE5LCJleHAiOjE3NTA2MDE4MTl9.zv9LVpOoJbse1FwYwCnAPVSqnuvJtVpPp8EHy-U7YS0

{
  "name":"mohammad",
  "password":"Mohammad",
  "courseName":"construction lab" ,
  "courseCode":"444"
}
###
POST http://localhost:8082/api/v1/login
Content-Type: application/json

{
  "name":"yazeded@gmail",
  "password":"password"
}

###
GET http://localhost:8080/api/v1/course