POST http://localhost:8082/api/v1/user 
Content-Type: application/vnd.api+json

{
  "data": {
    "type": "user",
    "attributes": {
      "name": "yazeded@gmail",
      "password": "password"
    }
  }
}

###
GET http://localhost:8080/api/v1/user

###
POST http://localhost:8082/api/v1/private/create-user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJ5YXplZWRAZ21haWwiLCJpYXQiOjE3NTAzNDEwMTUsImV4cCI6MTc1MDM0NDYxNX0.6rCd8GlGHW6htbI1MeSnR_jH0SgQElAJXCBWxbSAUV0

{
  "name":"kjdw",
  "password":"dkjwqn",
  "courseCode":"oxxi",
  "courseName":"ixxo" 
}
###
POST http://localhost:8082/api/v1/login
Content-Type: application/json

{
  "name":"yazeed@gmail",
  "password":"password"
}

###
GET http://localhost:8080/api/v1/course